import type { Metadata } from "next";
import "./globals.css";
import { Box } from "@mui/material";
import Header from "@/components/Common/Header";
import Footer from "@/components/Common/Footer";
import { Fira_Code, Source_Code_Pro } from "next/font/google";
import ThemeRegistry from "@/theme/themeRegistry";

const firaCode = Fira_Code({
  subsets: ['latin'],
  display: 'swap',
  weight: 'variable'
})

const sourceCodePro = Source_Code_Pro({
  subsets: ['latin'],
  display: 'swap',
  weight: 'variable'
})

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${firaCode.className} ${sourceCodePro.className} container`} >
        <ThemeRegistry options={{ key: 'mui-theme' }}>
          <Box sx={{
            height: '100%',
            width: '100%',
          }}>
            <Box sx={{
              height: '50px',
            }}>
              <Header />
            </Box>

            {children}

            <Box sx={{
              bottom: 0,
              left: 0,
            }}>
              <Footer />
            </Box>
          </Box>
        </ThemeRegistry>
      </body>
    </html>
  );
}
